name: travel_copilot
description: AI Travel Co-Pilot – Flutter mock-first MVP
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  equatable: ^2.0.5
  freezed_annotation: ^3.1.0
  flutter_map: ^8.2.2
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.4
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  io: ^1.0.4
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  supabase_flutter: ^2.10.1
  url_launcher: ^6.3.2
  flutter_dotenv: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^3.2.3
  flutter_launcher_icons: ^0.14.4
  json_serializable: ^6.9.2
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_fixed.png
    - assets/icons/signin_dark.png
    - assets/icons/signin_light.png
    - .env


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo_fixed.png
  remove_alpha_ios: true