name: travel_copilot
description: AI Travel Co-Pilot – Flutter mock-first MVP
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  intl: ^0.19.0
  supabase_flutter: ^2.10.1
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - /Users/mpmp/Desktop/Travel Co-Pilot/travel_copilot_mobile/assets/logo_fixed.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: /Users/mpmp/Desktop/Travel Co-Pilot/travel_copilot_mobile/assets/logo_fixed.png
  remove_alpha_ios: true